### PR TITLE
Fix #32: Replace Hy?go (typo) region in Japan with Hyogo

### LINKED ISSUE #32: text garbling in jp-all.geo.json.
I found text garbling or typo in map-collection-dist/countries/jp/jp-all.geo.json.

FYI
```
Wrong
name: "Hy?go",
Right
name: "Hyogo",

Wrong
woe-name: "Hy?go",
Right
woe-name: "Hyogo",
```

```
type: "Feature",
id: "JP.HG",
properties: {
hc-group: "admin1",
hc-middle-x: 0.53,
hc-middle-y: 0.46,
hc-key: "jp-hg",
hc-a2: "HG",
labelrank: "6",
hasc: "JP.HG",
alt-name: "Hiogo",
woe-id: "2345862",
subregion: null,
fips: "JA13",
postal-code: "HG",
name: "Hy?go",
country: "Japan",
type-en: "Prefecture",
region: "Kinki",
longitude: "134.837",
woe-name: "Hy?go",
latitude: "35.063",
woe-label: "Hyogo Prefecture, JP, Japan",
type: "Ken"
},
```

### PR DESCRIPTION
**Pull request by maor-refaeli**

### CODE REVIEW

**Comment by maor-refaeli** [comment]
Hey @jon-a-nygaard @KacperMadej @TorsteinHonsi ,
Made this small PR, please take a look if that is ok with you
Thanks

**Comment by TorsteinHonsi** [comment]
Thanks @maor-refaeli 

Unfortunately these files are generated, so your changes would probably be overwritten on the next release. @KacperMadej can we apply this to the sources?

**Comment by KacperMadej** [comment]
Applied a [fix](https://github.com/highcharts/map-collection/pull/36) to the source using Hyōgo as the correction for Hy?go.

**Comment by maor-refaeli** [comment]
Thanks @KacperMadej and @TorsteinHonsi !
I guess map-collection is a private repo, so I don't have access to it.
Can you share in a tag or a comment in which version is this fix expected to be released?
Also, please consider using `Hyogo` instead of `Hyōgo` to avoid accent mismatch (same as you don't have accent on all Japan's regions)

**Comment by KacperMadej** [comment]
@maor-refaeli 
We will be using `Hyogo` instead of `Hyōgo` to avoid accent mismatch - thank you for pointing this out.

> I guess map-collection is a private repo, so I don't have access to it.

The fix will be the same as commit.

> Can you share in a label or a comment in which version is this fix expected to be released?

The next version should have this fix. That should be v2.1.1 unless there will be a need for a more significant version change for the next release. I will add additional comment here when I will know more (version and date).

**Pull request closed without merging**
