### PR TITLE
fixed Uncaught TypeError when using this in grunt

### PR DESCRIPTION
**Pull request by ShiNoSenshi**
I used this file in my Gruntfile.js and got an Exception.
It is the same one, described in this stackoverflow post.
https://stackoverflow.com/questions/42036349/uncaught-typeerror-intermediate-value-is-not-a-function

### CODE REVIEW

**Comment by KacperMadej** [comment]
Hi @ShiNoSenshi 

Thank you for reporting the problem.

We had a similar issue with our export server and it was resolved as https://github.com/highcharts/node-export-server/commit/2d07efcab1ab37660228736a5e6a3196f64be617

We need to decide if we should add semicolons for every file ending, or should the problem be resolved in an environment that is using the map scripts.

Please check if the problems could be resolved in grunt @ShiNoSenshi

**Comment by ShiNoSenshi** [comment]
I was able to fix it by moving it to the last position in my Gruntfile.
Other js files seem not to have the issue.

**Comment by KacperMadej** [comment]
Thank you for checking this.

I'm not sure which other files have you tried, but all map JS files in our map collection are not having the `;` at the end, so the same problem should be visible for all the maps.

**Comment by KacperMadej** [comment]
We are generating maps based on sources and the changes are not done manually. This repository exists mainly for bug reporting and to release the map collection on NPM easily. I will create an issue about this in this report as the PR will be closed unless you would like to open the issue yourself (you will get notifications for any progress in the issue automatically, so I'm recommending this).

**Comment by ShiNoSenshi** [comment]
I used other javascript libaries provided by npm.
Feel free to close this PR and create an issue please. I'm fine with subscribing to the issue.

**Comment by KacperMadej** [comment]
https://github.com/highcharts/map-collection-dist/issues/45

**Pull request closed without merging**
